DIR1 = ../comb/
DIR2 = ../estructDatos/

all: arbolComb.o estructDatos.o

arbolComb.o:
	gcc -c $(DIR2)arbolComb.c -o $(DIR1)arbolComb.o

estructDatos.o:
	gcc -c $(DIR2)estructDatos.c -o $(DIR1)estructDatos.o
